name: Spring-Petclinic-Frontend-CICD

on:
  push:
    branches: [ frontend-cicd ]
  pull_request:
    branches: [ frontend-cicd ]

jobs:
  build:
    name: ci-cd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: test
#       - run: yarn install && echo "running yarn test success"
#       - name: package
#       - run: yarn install && yarn run dist
      - name: Build Docker Image and publish to ECR
        uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: team-github-action/petclinic-frontend
          region: us-east-1
          tags: latest,${{ github.sha }}
          create_repo: true
